In [ ]:
import numpy as np
a = np.array([1, 2, 3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
b = np.array([(2, 5, 7), (5, 3, 9), (4, 6, 5)])

In [ ]:
print(b)

[[2 5 7]
 [5 3 9]
 [4 6 5]]


In [ ]:
c = np.eye(10)
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
b.std()

1.9688939051854832